spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-manager-system?useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456


